# Generated by Django 2.2.2 on 2019-07-01 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_serverlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
