# Generated by Django 2.2.2 on 2019-07-02 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190702_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
