# Generated by Django 2.2.2 on 2019-07-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_selecttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Selecttest',
        ),
    ]
