# Generated by Django 2.2.2 on 2019-07-11 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20190711_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='login',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
