# Generated by Django 2.2.4 on 2019-08-11 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20190811_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='번역완료시간'),
        ),
    ]
