# Generated by Django 2.2.7 on 2019-11-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20190811_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transpost',
        ),
    ]
